version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${BOT_NAME}
    restart: always
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data: